version: "3"

tasks:
  run:
    desc: Runs the GO application
    cmds: 
      - go run cmd/main.go
  build:
    desc: Builds The GO Binary
    cmds:
      - go build -o main cmd/main.go
  test:
    desc: Runs Tests For Application
    cmds:
      - go test ./...
