version: "3"

tasks:
  run:
    desc: Runs the GO application
    cmds: 
      - go run nexpull.go
  build:
    desc: Builds The GO Binary
    cmds:
      - go build -o nexpull nexpull.go
  test:
    desc: Runs Tests For Application
    cmds:
      - go test .
  install:
    desc: Install the go binary on the system
    cmds:
      - go install nexpull.go
