name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Compile code
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - run: |
          echo "Compiling the code..."
          go build -v cmd/main.go
          echo "Compile complete."
  
  security:
    name: GO Snyk Check
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "latest"

      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          go test cmd/main_test.go
          echo "Unit Tests Complete"

  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 10
          echo "No lint issues found."

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "latest"

      - name: Deploy application
        run: |
          echo "Deploying application..."
          go build -v cmd/main.go
          echo "Application successfully deployed."
